name: Trigger Webhook on Push

on:
  push:
    branches:
      - main

jobs:
  trigger_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook
        uses: distributhor/webhook@v1
        with:
          url: https://a124-2401-4900-1c39-5b84-29e0-d4ae-3183-7f33.in.ngrok.io/github-webhook/
          method: POST
          contentType: application/json
          secret: ${{ secrets.POSTMAN_XRAY_WEBHOOK_SECRET }}
          body: |
            {
              "event_type": "api-dev-push",
              "client_payload": {
                "repository": "api-dev"
              }
            }
