name: Trigger Jenkins Job on Push in api-dev Repository

on:
  push:
    branches:
      - main

jobs:
  trigger_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Postman-Xray Webhook
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: singh-anamika/postman-xray
          event-type: trigger-webhook
          client-payload: '{"repository": {"name": "api-dev"}, "ref": "refs/heads/main", "url": "https://1ec9-2405-201-4028-2812-826c-1cf-e249-b534.in.ngrok.io/github-webhook/"}'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
