name: Trigger Webhook on Push

on:
  push:
    branches:
      - main

jobs:
  trigger_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.POSTMAN_XRAY_WEBHOOK_SECRET }}
          repository: singh-anamika/postman-xray
          event-type: 'trigger-webhook'
          client-payload: '{"url": "https://9b7a-2401-4900-1c39-5b84-9227-f687-fda8-fd9f.in.ngrok.io/github-webhook/"}'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
