name: Trigger API Automation 

on:
  push:
    branches:
      - main

jobs:
  trigger_automation:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API Automation Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: singh-anamika/postman-xray
          event-type: run_api_automation
