name: Trigger API Automation

on:
  push:
    branches:
      - main

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API Automation Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }}
          repository: OWNER_NAME/REPO_NAME
          event-type: EVENT_NAME
          client-payload: '{"some": "data"}'
